### ISSUE TITLE
 DLL load failed while importing nvdiffrast_plugin

### ISSUE THREAD

**Issue by ShockWave2048** [flowtyone/ComfyUI-Flowty-CRM#1]
Error occurred when executing CRMModelerCuda:

DLL load failed while importing nvdiffrast_plugin: Module not found
![Screenshot_1](https://github.com/flowtyone/ComfyUI-Flowty-CRM/assets/800625/875df8b3-668e-479c-94ff-c7b59b2e4fc3)

**Comment by flowtyone** [comment]
Yep, I knew there were gonna be issues with this dependency. Try to google 'how to install nvdiffrast'

**Comment by prezofpizza** [comment]
I'm getting a similar error 

"Error occurred when executing CRMModelerCuda:

No module named 'nvdiffrast.torch'"

I'm fairly certain I've installed it correctly, I can confirm the module can be found using a python script. For some reason it's not being seen in Comfy.

**Comment by ShockWave2048** [comment]
I couldn't find how to install this module. I can’t check the presence of a dll for Windows 11. How to install and download it in Windows? Python have this module, but not possible call dll.

**Comment by Falkonar** [comment]
> I couldn't find how to install this module. I can’t check the presence of a dll for Windows 11. How to install and download it in Windows? Python have this module, but not possible call dll.

Бро I've spend several days with reinstalling VS and cuda toolkit with cuddn . So C++ build tools. And it runs only with conda mini env (in my case) ...

**Comment by ShockWave2048** [comment]
[Falkonar](https://github.com/Falkonar) - have instructions for this?

**Comment by flowtyone** [comment]
Please see [troubleshooting](https://github.com/flowtyone/ComfyUI-Flowty-CRM/tree/master?tab=readme-ov-file#troubleshooting)

**Comment by ShockWave2048** [comment]
> Please see [troubleshooting](https://github.com/flowtyone/ComfyUI-Flowty-CRM/tree/master?tab=readme-ov-file#troubleshooting)

Thanks!

**Comment by EIegance** [comment]
For anyone coming across this looking for a fix; the only thing that solved it for me after **many** hours was:

- Switching off of ComfyUI portable version (Probably isn't necessary as long as you make sure you're not running cu118, just something I did)
- Uninstalling Torch, and everything related to cu118
- [Installing PyTorch cu112 ](https://pytorch.org/get-started/locally/)_specifically the nightly version_ 
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121`
- Then reinstalling Flowty-CRM + all of its requirements

I basically reinstalled everything and then made sure ComfyUI was running PyTorch 2.4.0+cu121. I doubt you'll have to do that as long as you fully switch your PyTorch version. But in case you still can't get it working id recommend starting fresh, and its easy if you still have your _ComfyUI_windows_portable_ to import everything from.
