### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by shiccup** [flowtyone/ComfyUI-Flowty-CRM#8]
Error occurred when executing CRMModeler:

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument grid in method wrapper_CUDA__grid_sampler_2d)

guessing i might have to move processes all onto my gpu? will troubleshoot

![image](https://github.com/flowtyone/ComfyUI-Flowty-CRM/assets/129121661/c8d2a4b8-3176-42f2-8381-d0a47163b882)

**Comment by flowtyone** [comment]
You only need to restart comfyui and run the cuda workflow. This error usually happens when you run the cpu workflow first by mistake

**Comment by bitcoinski** [comment]
Can confirm I'm getting this as well, can't run the cpu workflow after a fresh reboot

**Comment by flowtyone** [comment]
@bitcoinski do you have a cuda gpu?

**Comment by k0ta0uchi** [comment]
Hello!
I have issues with CUDA and decided to use cpu version workflow.
However, when I use cpu workflow, I get same error with this issue.
I rebooted comfyui, but no effect. Could you give me an advice??

**Comment by flowtyone** [comment]
@k0ta0uchi did you start comfyui with cpu-only?

**Comment by k0ta0uchi** [comment]
Oh, I totally forgot about that option!!
It workded!! Thank you so much!!

**Comment by bitcoinski** [comment]
@flowtyone running on Runpod w/ 
1 x RTX A4500
12 vCPU 62 GB RAM
